name: CI workflow

# Event triggers
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Jobs
jobs:
  build: # Name of the job
    runs-on: ubuntu-latest
    # Add a container where the CI pipeline will run on Python 3.9
    container: python:3.9-slim
